<?php
/**
 * Created by PhpStorm.
 * User: wali7
 * Date: 19/10/18
 * Time: 12:03
 */ ?>
<h2>Rédiger un nouvel article</h2>
<form action="/MetaSite/administration" method="post">
    <fieldset>
        <legend><i class="far fa-comment"></i> Nouvel article</legend>
        <div class="clear"></div>
        <table class="container">
            <tr>
                <td><label for="Titre">Titre: </label></td>
                <td><input type="text" name="Titre"></td>
            </tr>
            <tr>
                <td colspan="1"><label for="Article">Article: </label></td>
                <td><textarea name="Article" cols="30" rows="10"></textarea></td>
            </tr>
            <tr>
                <td colspan="1">
                    <label for="Auteur">Auteur: </label>
                </td>
                <td>
                    <select name="Auteur">
                        <?php foreach ($Auteurs as $auteur) { ?>
                            <option value="<?= $auteur['id'] ?>"><?= $auteur['Nom'] . ' ' . $auteur['Prenom'] ?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td colspan="1">
                    <label for="Categorie">Categorie: </label>
                </td>
                <td>
                    <select name="Categorie">
                        <?php foreach ($Categories as $Categorie) { ?>
                            <option value="<?= $Categorie['id'] ?>"><?= $Categorie['Nom_De_Categorie'] ?></option>
                        <?php } ?>

                    </select>
                </td>
            </tr>
            <tr>
                <td><p></p></td>
                <td>
                    <p>
                        <button type="submit" id="Ajouter" name="valide" value="valide">Ajouter</button>
                        <button type="reset" id="Annuler">Annuler</button>
                    </p>
                </td>
            </tr>

        </table>


    </fieldset>
</form>