    <?php ob_start();?>
    <main class="Content_Admin_home">

        <a href="/Restaurant/Admin/Meal" title="Editer la liste d'aliment disponible">
            Gestion des aliments
        </a>

        <a href="/Restaurant/Admin/Reservation" title="Rajout d'aliment a la liste disponible">
            Gestion des reservations
        </a>

        <a href="/Restaurant/Admin/Commandes" title="gestion des commande displonible">
            Gestion des commandes
        </a>

    </main>

<?php $content = ob_get_clean();
$title = 'page d\'administration';
require 'view/layout.phtml'; ?>