<h2><i class="fas fa-home"></i> Acceuil</h2>
<?php foreach ($Liste_News as $new) {
    $id = $new['id'];
    $titre = $new['titre'];
    $contenue = mb_substr($new['contenue'], 0, 100);
    $date_ajout = $new['date_ajout'];
    $nom_Auteur = $new['Nom'];
    $Prenom_Auteur = $new['Prenom'];
    $categorie = $new['Nom_De_Categorie'];
    ?>
    <div class="Post">
        <a href="/MetaSite/Commentaires/<?= $id ?>">
            <h3>
                <i class="far fa-hand-point-right" style="color:black;"></i>
                <?= $titre ?>
            </h3>
        </a>
        <p>
            <?= $contenue ?>
            <a href="/MetaSite/Commentaires/<?= $id ?>" class="<?= $id ?>"
               style="color:black;">[...]</a>
        </p>
        <p>
            Rédigé par  <?php if ($nom_Auteur == null){ echo '<strong>Auteur suprimé</strong>'; } else { echo $nom_Auteur . ' ' . $Prenom_Auteur; }  ?> le <?= $date_ajout ?>
        </p>
    </div>

<?php } ?>
