
<link rel="stylesheet" type="text/css" href="/www/Realization/meta_site/css/Ardoise_Magique.css">

    <h1><i class="fas fa-paint-brush"></i>ardoise magique</h1>
    <section id="core_elements">
        <canvas id="content" width="800" height="600"></canvas>

        <div id="outils">
            <h4>outils</h4>
            <div>
                <button id="Gomme" title="Gomme"><i class="fas fa-eraser"></i></button>
                <button id="pipette" title="Pipette"><i class="fas fa-eye-dropper"></i></button>
                <button id="eraser" title="effacer le dessein">reset</button>
                <p><span id="colo_selected"></span></p>
                <p>
                    <input type="range" min="1" max="50">
                    <span id="output"></span>
                </p>
                <select id="effects" title="effets tracée">
                    <option value="pencil">pencil</option>
                    <option value="brush">brush</option>
                    <option value="toile">toile</option>
                    <option value="rectangle">rectangle</option>
                </select>
                <span title="effet ombres">shadow : <input id="shadow" type="checkbox"></span>
                <canvas id="palette" width="170px" height="50"></canvas>
            </div>

        </div>


    </section>

    <article id="Couleurs">
        <div id="black" title="Couleur noir" data-colo="black"></div>
        <div id="Brown" title="Couleur marron" data-colo="brown"></div>
        <div id="Red" title="Couleur rouge" data-colo="red"></div>
        <div id="Yellow" title="Couleur jaune" data-colo="yellow"></div>
        <div id="Green" title="Couleur vert" data-colo="green"></div>
        <div id="blueSoft" title="Couleur blue ciel" data-colo="deepskyblue"></div>
        <div id="blueHard" title="Couleur bleu foncé" data-colo="blue"></div>
    </article>



<script src="/www/Realization/meta_site/js/Ardoise_Magique/js/class/Ardoise.class.js"></script>
<script src="/www/Realization/meta_site/js/Ardoise_Magique/js/class/Palette.class.js"></script>
<script src="/www/Realization/meta_site/js/Ardoise_Magique/js/class/pen.class.js"></script>
<script src="/www/Realization/meta_site/js/Ardoise_Magique/js/class/program.class.js"></script>
<script src="/www/Realization/meta_site/js/Ardoise_Magique/js/main.js"></script>