<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $title ?></title>
    <link rel="stylesheet" href="/www/Realization/restaurant/public/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="/www/Realization/restaurant/public/vendors/fontawesome5.5/css/all.css">
    <link rel="stylesheet" href="/www/Realization/restaurant/public/css/GoHome.css">
    <link rel="stylesheet" href="/www/Realization/restaurant/public/css/main.css">
    <?php if (isset($_SESSION['admin'])) { ?>
        <link rel="stylesheet" href="/www/Realization/restaurant/public/css/admin.css">
        <?php }?>
    <script src="/www/Realization/restaurant/public/js/main.js"></script>
</head>
<body>
<a href="/home" id="home">
    <i class="fas fa-home"></i>
</a>
<div id="red"></div>
<header>
    <h1><a href="/Restaurant">Restaurant - Made in America</a></h1>
    <div id="login_group">
        <?php if (!isset($_SESSION['user']) && !isset($_SESSION['admin'])) { ?>
            <a href="/Restaurant/Inscription">créer un compte</a>
            <a id="Connexion" class="active">Connexion</a>
            <section id="section_connexion" style="display: none">
                <form action="/Restaurant/Connexion" method="post">
                    <input type="text" placeholder="email" name="email" id="email">
                    <input type="password" placeholder="Mot de passe" name="mdp">
                    <button class="active" type="submit" name="Connexion">Connexion</button>
                </form>
            </section>
        <?php } elseif (isset($_SESSION['user'])) {
            global $ConectedUser; ?>
            <a href="/Restaurant/MonCompte">Mon compte</a>
            <a href="/Restaurant/reservation">Reserver une table</a>
            <a href="/Restaurant/order">commander des aliments</a>
            
          <div><?php $user = $_SESSION['user'];echo '<p>bonjour </p>'.'  <span><a href="/Restaurant/MonCompte"> '.' '.$ConectedUser -> getnom().' '.$ConectedUser -> getprenom().'</a></span>' ?></div>
           <a href="/Restaurant/Deconexion" >Deconnexion</a>
        <?php } elseif (isset($_SESSION['admin'])) { ?>
            <a href="/Restaurant/Deconexion" >Deconnexion</a>

        <?php } ?>
    </div>
</header>
<?php $message_info = checkErrors(); 
    if (isset($message_info)) {
            echo $message_info;
        $message_info = null;
        echo '<script src="/www/Realization/restaurant/public/js/afficherMessageInfo.js"></script>';
    } else {
        echo'<div id="message_info">        </div>';
    } //affiche les message d'erreur / reussite
    ?>
<?= $content ?>
<footer>
    <img src="/www/Realization/restaurant/public/images/payment/mastercard.png" alt="mastercard">
    <img src="/www/Realization/restaurant/public/images/payment/paypal.png" alt="paypal">
    <img src="/www/Realization/restaurant/public/images/payment/visa.png" alt="visa">
    <p>Yaci</p>
</footer>
</body>
</html>